#!/bin/bash

# Set file to store credentials
usersFile=".users"

# Get username and password from arguments
username="$1"
password="$2"

function check_user_exists() {
    grep -q "^$username:" $usersFile
}

function delete_empty_file() {

    if [[ ! -f "$usersFile" ]]; then
        echo "File '$usersFile' not found."
        return 1
    fi

    while IFS= read -r line; do
        if [[ -n "$line" ]]; then
            return 0  # Non-empty line found
        fi
    done < "$usersFile"

    # If the loop completes without returning, the file is empty
    rm -f "$usersFile" "$usersFile.tmp" 2> /dev/null
    echo "'$username' was the last credential"
    echo "Uploads are now disabled."
}

# Check for required arguments
if [ $# -ne 2 ]; then

    echo -e "Single File PHP File Browser"
    echo -e "User management usage:"
    echo -e "Add user: $0 username password"
    echo -e "Del user: $0 username --delete"
    exit 1

# Check if it's a deletion
elif [ "$password" = "--delete" ]; then

    if [ -f $usersFile ]; then
        # Get username from arguments and remove from users file
        grep -v "$username:" $usersFile > $usersFile.tmp && mv $usersFile.tmp $usersFile
        echo -e "User '$username' deleted."
    fi
    delete_empty_file
    exit 0

# Proceed to user creation
else

    # Check if the user already exists
    if [ -f $usersFile ] && check_user_exists "$username"; then
        echo "User '$username' already exists."
        echo -e "If that's you, use: $0 $username --delete and try again."
        exit 1

    else

        # Hash the password using PHP
        hashedPassword=$(php -r "echo password_hash('$password', PASSWORD_DEFAULT);")
        if [ ! -f $usersFile ]; then echo "Uploads are now enabled."; fi
        # If credentials are on the very first line of the file,
        # This script is unable to remove it later for some reason.
        # So we echo an empty line to overcome this.
        echo "" >> $usersFile 
        # Append the user and hashed password to the users file
        echo "$username:$hashedPassword" >> $usersFile
        echo -e "User '$username' added."
        exit 0

    fi
fi